import assert from 'node:assert/strict';
import {runScenario,captureScreenshot} from './browser-harness.mjs';
await runScenario('audio-settings',5184,async({page,url,artifactDir})=>{
 await page.addInitScript(()=>{const Native=window.AudioContext;window.audioContexts=0;window.AudioContext=class extends Native{constructor(...args){super(...args);window.audioContexts++;window.audioContext=this;}};});
 const musicRequests=[];page.on('request',r=>{if(/\.(mp3|ogg|wav)(\?|$)/.test(r.url()))musicRequests.push(r.url());});
 await page.goto(url);await page.locator('#tap-to-play').waitFor();
 assert.equal(await page.evaluate(()=>window.audioContexts),0,'Preloading/title must not create AudioContext');
 assert.equal(await page.locator('#begin').count(),0,'Menu must not mount before user intent');
 await page.locator('#tap-to-play').click();await page.locator('#begin').waitFor();
 assert.equal(await page.evaluate(()=>window.audioContexts),1,'Tap to Play must own the one shared AudioContext');
 await page.locator('#sound').click();await page.locator('#sound').click();assert.equal(await page.evaluate(()=>window.audioContexts),1,'Later gestures reuse the shared context');
 await page.locator('#begin').click();await page.locator('#pause').click();
 await page.waitForFunction(()=>window.audioContext.state==='suspended');
 for(let i=0;i<6;i++)await page.locator('#sound').click();
 await page.waitForFunction(()=>window.audioContext.state==='suspended');
 assert.equal(await page.evaluate(()=>window.audioContexts),1,'Paused settings reuse the suspended context');
 await page.locator('#motion-setting').check();await page.locator('#haptics-setting').check();
 await page.locator('#effects-volume').focus();await page.keyboard.press('Home');await page.keyboard.press('ArrowRight');
 await page.locator('#sound').click();await captureScreenshot(page,`${artifactDir}/settings.png`);
 await page.reload();await page.locator('#tap-to-play').waitFor();assert.equal(await page.evaluate(()=>window.audioContexts),0,'Reload stays silent until title intent');
 await page.locator('#tap-to-play').click();await page.locator('#begin').waitFor();assert.equal(await page.locator('#sound').textContent(),'Sound off');
 const settings=await page.evaluate(()=>JSON.parse(localStorage.getItem('nailz-settings-v1')));assert.equal(settings.effects,.05);assert.equal(settings.reducedMotion,true);assert.equal(settings.haptics,true);
 assert.deepEqual(musicRequests,[],'Absent music must make no audio file requests');
 await page.addInitScript(()=>{window.AudioContext=class {constructor(){throw Error('Audio denied');}};});
 await page.goto(url+'/?quality=low');await page.locator('#tap-to-play').waitFor();await page.locator('#tap-to-play').click();await page.locator('#begin').waitFor();
 await page.locator('#begin').click();assert.notEqual(await page.locator('#app').getAttribute('data-phase'),'MATCH_INTRO','Audio failure cannot block play');
});
